#80 Private post in inbox, deleted print
CMPUT404W22-SocialDistribution/social-distribution pull request #84
Opened 2022-03-19 20:25 UTC by HolaClubSandwich

2022-03-19 21:04 UTC, vhnguyen0707 requested changes

2022-03-19 21:04 UTC, vhnguyen0707 commented on social_distribution/posts/views.py
> +                    if post.visibleTo == str(friend.user):
- If you want to create private post for friends and followers only. You should be checking if the recipient is valid when you attempt to create the post already, not when you’re done creating post then inbox.
- You shouldn’t be converting an user object into string like this. A more Django and pythonic way is using user.username

2022-03-19 21:04 UTC, vhnguyen0707 commented on social_distribution/posts/views.py
> +                # if users are friend
- Friends are also followers so  if you do 2 for loops like this, there will inherently be duplicates.
- It is not very optimal to traverse through the whole queryset, and check if the usernames are matching, just get author object of the recipient and check if it is in the followers list.

2022-03-19 22:02 UTC, HolaClubSandwich commented on social_distribution/posts/views.py
> +                    if post.visibleTo == str(friend.user):
User can still create private post to non friend or unfollowed users tho?

2022-03-19 22:14 UTC, vhnguyen0707 commented on social_distribution/posts/views.py
> +                    if post.visibleTo == str(friend.user):
Then why would you inbox to friends or followers only? If the recipient is not friend or follower, the only way to see the post is having the uri or it shows up on new feed. But there are lots of public and friend posts from local and the other 3 remote nodes. It is more even unlikely to see it and it’s not a good design UX-wise.

2022-03-19 22:15 UTC, HolaClubSandwich commented on social_distribution/posts/views.py
> +                    if post.visibleTo == str(friend.user):
I thought inbox is only showing friends and followers post update?

2022-03-19 22:20 UTC, HolaClubSandwich commented on social_distribution/posts/views.py
> +                    if post.visibleTo == str(friend.user):
Oh right, my bad, I understand it now

2022-03-20 20:19 UTC, vhnguyen0707 approved these changes

2022-03-20 20:31 UTC, merged